// Document → Form import (Phase 1 / MVP): upload a PDF, Word doc, or image
// of a form and get back a real Flowora form, generated by AI. Everything
// happens inline within the request (no queue/worker/cloud storage) — the
// upload lives only in memory (multer memoryStorage) for the duration of
// this one request, and nothing about the original file is ever persisted.
const express = require("express");
const multer = require("multer");
const mammoth = require("mammoth");
const { randomUUID: uuid } = require("crypto");
const { scopedCollection } = require("../db/store");
const { requireManager } = require("../middleware/auth");
const aiClient = require("../integrations/aiClient");
const { getLimitsForAccount, getAiProviderForAccount } = require("./settings");
const { hasEnoughCredits, deductCredits, CREDIT_COSTS } = require("../utils/aiCredits");
const { isGoogleFormUrl, fetchGoogleForm } = require("../integrations/googleFormsClient");

const router = express.Router();
const formsFor = (req) => scopedCollection("forms", req.user.accountId);

const MAX_FILE_BYTES = 20 * 1024 * 1024; // 20MB, matches the architecture doc's cap
const ACCEPTED_MIME_TYPES = new Set([
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document", // .docx
  "image/png",
  "image/jpeg",
  "image/webp",
]);

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_FILE_BYTES },
  fileFilter: (req, file, cb) => {
    // Reject early (before the body is even fully read) rather than
    // downloading a .exe/.zip into memory just to reject it after the fact.
    cb(null, ACCEPTED_MIME_TYPES.has(file.mimetype));
  },
});

// Strips the noise a real-world PDF/Word extraction leaves behind (repeated
// blank lines, stray page-number lines) before it ever reaches the model —
// fewer tokens, and a cleaner signal for the AI to extract fields from.
function cleanText(raw) {
  return raw
    .replace(/\r/g, "")
    .replace(/^\s*(page\s+)?\d+\s*(of\s*\d+)?\s*$/gim, "")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

async function extractText(file) {
  if (file.mimetype === "application/pdf") {
    // Required lazily — pdf-parse's own test-fixture-loading side effect
    // at module scope has bitten other projects when required eagerly at
    // boot without its (irrelevant, dev-only) sample PDF present.
    const pdfParse = require("pdf-parse");
    const data = await pdfParse(file.buffer);
    return data.text || "";
  }
  const { value } = await mammoth.extractRawText({ buffer: file.buffer });
  return value || "";
}

// Wraps multer's own middleware so a rejected/oversized upload comes back
// as this app's normal `{ error }` JSON shape instead of falling through to
// Express's default (HTML) error page — there's no global error handler
// elsewhere in this app to catch it otherwise.
function handleUpload(req, res, next) {
  upload.single("file")(req, res, (err) => {
    if (err instanceof multer.MulterError && err.code === "LIMIT_FILE_SIZE") {
      return res.status(413).json({ error: "That file is over the 20MB limit." });
    }
    if (err) return res.status(400).json({ error: "Couldn't read that upload — try again." });
    next();
  });
}

// Importing a form (from a file or a URL) is just another way to spend an
// AI credit, so it's gated the same way as the AI Assistant / "Generate
// with AI" flow (forms.js) — plan tier first (Growth+ only), then credit
// balance on top of that.
// Returns an { status, error, code } pair to send as-is, or null if OK.
async function checkImportAllowed(req) {
  if (req.user.isMasterAdmin) return null;
  const limits = await getLimitsForAccount(req.user.accountId);
  if (!limits.aiAssistant) {
    return { status: 403, code: "plan_required", error: `Importing forms with AI requires the Growth plan or higher. Your account is on ${limits.label}.` };
  }
  if (!(await hasEnoughCredits(req.user.accountId, "documentImport"))) {
    return {
      status: 403,
      code: "insufficient_credits",
      error: `You don't have enough AI credits for this (needs ${CREDIT_COSTS.documentImport}). Upgrade your plan for more.`,
    };
  }
  const formCount = (await formsFor(req).all()).length;
  if (formCount >= limits.maxForms) {
    return { status: 403, error: `Your plan (${limits.label}) allows up to ${limits.maxForms} form${limits.maxForms === 1 ? "" : "s"}. Upgrade to create more.` };
  }
  return null;
}

async function resolveAiProvider(req) {
  const provider = await getAiProviderForAccount(req.user.accountId);
  if (!aiClient.isConfigured(provider)) {
    const providerLabel = provider === "gemini" ? "Gemini" : "Anthropic";
    const envVar = provider === "gemini" ? "GEMINI_API_KEY" : "ANTHROPIC_API_KEY";
    throw Object.assign(new Error(`${providerLabel} isn't configured yet. Ask your admin to set ${envVar} in the backend environment.`), { status: 503 });
  }
  return provider;
}

async function saveImportedForm(req, extracted) {
  const form = {
    id: uuid(),
    name: extracted.title,
    description: extracted.description || "",
    fields: extracted.fields.map((f) => ({ ...f, id: uuid() })),
    settings: { submitButtonText: "Submit", confirmationMessage: "Thanks for your submission!" },
    status: "Draft",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
  await formsFor(req).insert(form);
  if (!req.user.isMasterAdmin) await deductCredits(req.user.accountId, req.user.id, "documentImport", { formId: form.id });
  return form;
}

router.post("/", requireManager, handleUpload, async (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: "Upload a PDF, Word (.docx), or image (PNG/JPEG/WebP) file under 20MB." });
  }

  const gateError = await checkImportAllowed(req);
  if (gateError) return res.status(gateError.status).json({ error: gateError.error, code: gateError.code });

  let provider;
  try {
    provider = await resolveAiProvider(req);
  } catch (err) {
    return res.status(err.status || 503).json({ error: err.message });
  }

  const isImage = req.file.mimetype.startsWith("image/");

  try {
    let extracted;
    if (isImage) {
      // No OCR step — Gemini Vision reads the layout (checkboxes, radio
      // groups, labels) directly from the image. Anthropic doesn't have
      // this path wired up yet (see aiProviders/anthropic.js) and errors
      // out clearly if picked with an image.
      extracted = await aiClient.extractFormFromDocument({
        provider,
        imageBase64: req.file.buffer.toString("base64"),
        imageMimeType: req.file.mimetype,
      });
    } else {
      const rawText = await extractText(req.file);
      const text = cleanText(rawText);
      if (!text) {
        return res.status(400).json({ error: "Couldn't read any text from that file — it may be a scanned/image-only PDF. Try uploading it as an image instead." });
      }
      extracted = await aiClient.extractFormFromDocument({ provider, text });
    }

    if (extracted.fields.length === 0) {
      return res.status(422).json({ error: extracted.description || "Couldn't find any fillable fields in that document." });
    }

    const form = await saveImportedForm(req, extracted);
    res.status(201).json({ ...form, accountId: req.user.accountId });
  } catch (err) {
    const status = /rate-limited|quota/i.test(err.message) ? 429 : 502;
    res.status(status).json({ error: err.message });
  }
});

// Import from an external form builder by URL. Only Google Forms works
// today (see integrations/googleFormsClient.js for why — no read API for
// someone else's form, so this scrapes the page's embedded data instead).
// Typeform/Tally have real APIs but need the account's own API key/OAuth
// token to read a form they own — not supported yet, hence the explicit
// "not supported" branch below rather than silently failing.
router.post("/url", requireManager, async (req, res) => {
  const { provider: source, url } = req.body;
  if (!url || typeof url !== "string") {
    return res.status(400).json({ error: "url is required." });
  }
  if (source !== "google") {
    return res.status(400).json({ error: `Importing from "${source || "that provider"}" isn't supported yet — only Google Forms right now.` });
  }
  if (!isGoogleFormUrl(url)) {
    return res.status(400).json({ error: "That doesn't look like a Google Form link — expected something like https://docs.google.com/forms/d/e/.../viewform." });
  }

  const gateError = await checkImportAllowed(req);
  if (gateError) return res.status(gateError.status).json({ error: gateError.error, code: gateError.code });

  let provider;
  try {
    provider = await resolveAiProvider(req);
  } catch (err) {
    return res.status(err.status || 503).json({ error: err.message });
  }

  try {
    const googleForm = await fetchGoogleForm(url);
    const text = cleanText(
      `Form title: ${googleForm.title}\n${googleForm.description}\n\n` +
        googleForm.questions
          .map((q, i) => {
            const lines = [`${i + 1}. ${q.label}${q.required ? " (required)" : ""}`];
            if (q.helpText) lines.push(`   Help text: ${q.helpText}`);
            if (q.options.length) lines.push(`   Options: ${q.options.join(", ")}`);
            return lines.join("\n");
          })
          .join("\n\n")
    );

    const extracted = await aiClient.extractFormFromDocument({ provider, text });
    if (extracted.fields.length === 0) {
      return res.status(422).json({ error: "Couldn't turn that form's questions into fields — it may use a question type this importer doesn't understand yet." });
    }

    // Use the title scraped straight from Google, not Gemini's guess — Gemini
    // is only trusted to normalize/type the *fields*, not to rename the form;
    // asking it to also infer a title from a text blob risks it paraphrasing
    // or genericizing a name we already know exactly, verbatim, from the source.
    const form = await saveImportedForm(req, { ...extracted, title: googleForm.title || extracted.title });
    res.status(201).json({ ...form, accountId: req.user.accountId });
  } catch (err) {
    const status = /rate-limited|quota/i.test(err.message) ? 429 : err.status || 502;
    res.status(status).json({ error: err.message });
  }
});

module.exports = router;
