// Document → Form import (Phase 1 / MVP): upload a PDF, Word doc, or image
// of a form and get back a real Flowora form, generated by AI. Everything
// happens inline within the request (no queue/worker/cloud storage) — the
// upload lives only in memory (multer memoryStorage) for the duration of
// this one request, and nothing about the original file is ever persisted.
const express = require("express");
const multer = require("multer");
const mammoth = require("mammoth");
const { randomUUID: uuid } = require("crypto");
const { scopedCollection } = require("../db/store");
const { requireManager } = require("../middleware/auth");
const aiClient = require("../integrations/aiClient");
const { getLimitsForAccount, getAiProviderForAccount, getAiUsage, incrementAiUsage } = require("./settings");

const router = express.Router();
const formsFor = (req) => scopedCollection("forms", req.user.accountId);

const MAX_FILE_BYTES = 20 * 1024 * 1024; // 20MB, matches the architecture doc's cap
const ACCEPTED_MIME_TYPES = new Set([
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document", // .docx
  "image/png",
  "image/jpeg",
  "image/webp",
]);

const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: MAX_FILE_BYTES },
  fileFilter: (req, file, cb) => {
    // Reject early (before the body is even fully read) rather than
    // downloading a .exe/.zip into memory just to reject it after the fact.
    cb(null, ACCEPTED_MIME_TYPES.has(file.mimetype));
  },
});

// Strips the noise a real-world PDF/Word extraction leaves behind (repeated
// blank lines, stray page-number lines) before it ever reaches the model —
// fewer tokens, and a cleaner signal for the AI to extract fields from.
function cleanText(raw) {
  return raw
    .replace(/\r/g, "")
    .replace(/^\s*(page\s+)?\d+\s*(of\s*\d+)?\s*$/gim, "")
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

async function extractText(file) {
  if (file.mimetype === "application/pdf") {
    // Required lazily — pdf-parse's own test-fixture-loading side effect
    // at module scope has bitten other projects when required eagerly at
    // boot without its (irrelevant, dev-only) sample PDF present.
    const pdfParse = require("pdf-parse");
    const data = await pdfParse(file.buffer);
    return data.text || "";
  }
  const { value } = await mammoth.extractRawText({ buffer: file.buffer });
  return value || "";
}

// Wraps multer's own middleware so a rejected/oversized upload comes back
// as this app's normal `{ error }` JSON shape instead of falling through to
// Express's default (HTML) error page — there's no global error handler
// elsewhere in this app to catch it otherwise.
function handleUpload(req, res, next) {
  upload.single("file")(req, res, (err) => {
    if (err instanceof multer.MulterError && err.code === "LIMIT_FILE_SIZE") {
      return res.status(413).json({ error: "That file is over the 20MB limit." });
    }
    if (err) return res.status(400).json({ error: "Couldn't read that upload — try again." });
    next();
  });
}

router.post("/", requireManager, handleUpload, async (req, res) => {
  if (!req.file) {
    return res.status(400).json({ error: "Upload a PDF, Word (.docx), or image (PNG/JPEG/WebP) file under 20MB." });
  }

  // Same plan gates as the AI Assistant / "Generate with AI" flow (forms.js,
  // /:id/ai/build) — importing a document is just another way to spend an
  // AI generation, so it shouldn't be a free side door around that limit.
  if (!req.user.isMasterAdmin) {
    const limits = await getLimitsForAccount(req.user.accountId);
    if (!limits.aiAssistant) {
      return res.status(403).json({ error: `Importing forms with AI requires the Growth plan or higher. Your account is on ${limits.label}.` });
    }
    const usage = await getAiUsage(req.user.accountId);
    if (usage.used >= usage.limit) {
      return res.status(403).json({ error: `You've used all ${usage.limit} AI generations included this month. It resets on the 1st.` });
    }
    const formCount = (await formsFor(req).all()).length;
    if (formCount >= limits.maxForms) {
      return res.status(403).json({ error: `Your plan (${limits.label}) allows up to ${limits.maxForms} form${limits.maxForms === 1 ? "" : "s"}. Upgrade to create more.` });
    }
  }

  const provider = await getAiProviderForAccount(req.user.accountId);
  if (!aiClient.isConfigured(provider)) {
    const providerLabel = provider === "gemini" ? "Gemini" : "Anthropic";
    const envVar = provider === "gemini" ? "GEMINI_API_KEY" : "ANTHROPIC_API_KEY";
    return res.status(503).json({ error: `${providerLabel} isn't configured yet. Ask your admin to set ${envVar} in the backend environment.` });
  }

  const isImage = req.file.mimetype.startsWith("image/");

  try {
    let extracted;
    if (isImage) {
      // No OCR step — Gemini Vision reads the layout (checkboxes, radio
      // groups, labels) directly from the image. Anthropic doesn't have
      // this path wired up yet (see aiProviders/anthropic.js) and errors
      // out clearly if picked with an image.
      extracted = await aiClient.extractFormFromDocument({
        provider,
        imageBase64: req.file.buffer.toString("base64"),
        imageMimeType: req.file.mimetype,
      });
    } else {
      const rawText = await extractText(req.file);
      const text = cleanText(rawText);
      if (!text) {
        return res.status(400).json({ error: "Couldn't read any text from that file — it may be a scanned/image-only PDF. Try uploading it as an image instead." });
      }
      extracted = await aiClient.extractFormFromDocument({ provider, text });
    }

    if (extracted.fields.length === 0) {
      return res.status(422).json({ error: extracted.description || "Couldn't find any fillable fields in that document." });
    }

    const form = {
      id: uuid(),
      name: extracted.title,
      description: extracted.description || "",
      fields: extracted.fields.map((f) => ({ ...f, id: uuid() })),
      settings: { submitButtonText: "Submit", confirmationMessage: "Thanks for your submission!" },
      status: "Draft",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    await formsFor(req).insert(form);
    if (!req.user.isMasterAdmin) await incrementAiUsage(req.user.accountId);

    res.status(201).json({ ...form, accountId: req.user.accountId });
  } catch (err) {
    const status = /rate-limited|quota/i.test(err.message) ? 429 : 502;
    res.status(status).json({ error: err.message });
  }
});

module.exports = router;
